WebApp/Models/HomeModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class HomeModel
    {
        [Required(ErrorMessage = "Username Is Empty")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Password Is Empty")]
        public string Password { get; set; }

        public HomeModel(string username, string password)
        {
            this.Username = username;
            this.Password = password;
        }
    }
}

WebApp/Models/RegisterModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class RegisterModel
    {
        [Required]
        public string Username { get; set; }

        [Required]
        public string FullName { get; set; }

        [Required]
        public string Password { get; set; }

        [Compare("Password", ErrorMessage = "Confirm password doesn't match, Type again !")]
        public string ConfirmPassword { get; set; }

        [Required]
        public string Email { get; set; }

        [Compare("Email", ErrorMessage = "Confirm email doesn't match, Type again !")]
        public string ConfirmEmail { get; set; }

        [Required]
        public HttpPostedFileBase UploadImage { get; set; }

        public RegisterModel(string username, string fullname, string password, string email, HttpPostedFileBase uploadimage)
        {
            this.Username = username;
            this.FullName = fullname;
            this.Password = password;
            this.Email = email;
            this.UploadImage = uploadimage;
        }
    }


}

WebApp/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace WebApp.Models
{
    public class UserModel
    {
        public string Username { get; set; }
        public string Password { get; set; }

        public UserModel(string username, string password)
        {
            this.Username = username;
            this.Password = password;
        }
    }
}

WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;
using WebApp.TechSupportServiceReference;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApp/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TechSharedLibraries;
using WebApp.Models;
using WebApp.TechSupportServiceReference;
using System.IO;

namespace WebApp.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        public ActionResult Index()
        {
            return View("RegisterIndex");
        }

        [HttpPost]
        public async Task<ActionResult> Registration(string username, string fullname, string password, string email, HttpPostedFileBase uploadimage) //HttpPostedFileBase
        {
            using (TechSupportService1Client client = new TechSupportService1Client())
            {
                string fileName = Path.GetFileName(uploadimage.FileName);
                string path = Server.MapPath("~//Temp//");
                uploadimage.SaveAs(path + fileName);

                client.Open();
                string uploadedFile = "";
                if (uploadimage != null)
                {
                    uploadedFile = await AzureBlobUploader.UploadImageAsync(path);
                }
                client.RegisterNewUser(fullname, email, username, password, uploadedFile);
            }

            return View(new RegisterModel(username, fullname, password, email, uploadimage));
        }

        private async Task<string> Upload(string file)
        {
            return await AzureBlobUploader.UploadImageAsync(file);
        }
        
    }
}

WebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;
using WebApp.TechSupportServiceReference;

namespace WebApp.Controllers
{
    public class UserController : Controller
    {

        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            using (TechSupportService1Client client = new TechSupportService1Client())
            {               
                if (client.UserLogin(username, password))
                {                   
                    return View(new UserModel(username, password));
                }
                else
                {
                    return View("~/Views/Home/index.cshtml"); //TODO: incorrect username or password
                }
            }
        }
    }
}

WebApp/Views/Home/Index.cshtml
@{
    Page.Title = "Index page";
}

@model WebApp.Models.HomeModel

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
</head>
<body>

@using (Html.BeginForm("Login", "User", FormMethod.Post))
{

    <div class="container">
        <div class="login">
            <h1 class="login-heading">
                <strong>Welcome.</strong> Please login.
            </h1>
            <form method="post">
                @Html.TextBoxFor(m => m.Username, new { @class = "input-txt", placeholder = "Username", autocomplete = "off" })
                @*@Html.ValidationMessageFor(m => m.Username)*@
                @Html.PasswordFor(m => m.Password, new { @class = "input-txt", placeholder = "Password" })
                @*@Html.ValidationMessageFor(m => m.Password)*@
                <div class="login-footer">                  
                    <button type="button" class="btn" onclick="location.href='@Url.Action("Index", "Register")'">Registration</button>
                    <input type="submit" class="btn" value="Sign in" />               
                </div>
            
                <div class="lnkdiv">
                    <a href="#hovamenjen a link" class="lnk">
                        I forgot my password...
                    </a>
                </div>
            
            </form>
        </div>
    </div>
}
</body>
</html>

WebApp/Views/Register/RegisterIndex.cshtml
@{
    Page.Title = "RegisterIndex page";
}

@model WebApp.Models.RegisterModel

@*<h1>Hello World! Register/RegisterIndex.cshtml</h1>*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

    <style>

    </style>

</head>

<body>


    @using (Html.BeginForm("Registration", "Register", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div class="container">
            <div class="login">
                <h1 class="login-heading">
                    <strong>Registration</strong>
                </h1>
                <form method="post">

                    @Html.TextBoxFor(m => m.Username, new { @class = "input-txt", placeholder = "Username", autocomplete = "off" })
                    @*@Html.ValidationMessageFor(m => m.Username)*@
                    @Html.TextBoxFor(m => m.FullName, new { @class = "input-txt", placeholder = "Full Name", autocomplete = "off" })
                    @*@Html.ValidationMessageFor(m => m.Username)*@
                    @Html.PasswordFor(m => m.Password, new { @class = "input-txt", placeholder = "Password" })
                    @*@Html.ValidationMessageFor(m => m.Password)*@
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "input-txt", placeholder = "Password Again" })
                    @*@Html.ValidationMessageFor(m => m.ConfirmPassword)*@
                    @Html.TextBoxFor(m => m.Email, new { @class = "input-txt", placeholder = "Email", autocomplete = "off", @type = "email" })
                    @*@Html.ValidationMessageFor(m => m.Email)*@
                    @Html.TextBoxFor(m => m.ConfirmEmail, new { @class = "input-txt", placeholder = "Email Again", autocomplete = "off" })
                    @*@Html.ValidationMessageFor(m => m.ConfirmEmail)*@





                    @Html.TextBoxFor(m => m.UploadImage, new { type = "file" })



                    <div class="login-footer">
                        <input type="submit" class="btn" value="Registration" />
                    </div>

                </form>
            </div>
        </div>


        @* Registration *@
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.js"></script>
        <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.js"></script>
        <script src="//ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.js"></script>
    }

</body>
</html>

WebApp/Views/Register/Registration.cshtml
@{
    Page.Title = "Registration page";
}


<h1>@Model.Username</h1>
<h1>@Model.Password</h1>
<h1>@Model.Email</h1>
<h1>@Model.UploadImage</h1>

@*<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Registration</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>*@

WebApp/Views/Shared/_Main.cshtml
<!DOCTYPE html>

<html>
<head>
    @RenderSection("head", false)
    <link rel="stylesheet" href="/css/style.css">

    @* Signalr *@
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.6.4.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.signalR-2.1.0.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/signalr/hubs")"></script>

</head>
<body>

    @RenderBody()

</body>
</html>

WebApp/Views/User/Login.cshtml
@model WebApp.Models.UserModel

<!DOCTYPE html>
<html>
<head>
    <title>Welcome @Model.Username</title>
    <style type="text/css">
        .container {
            background-color: #99CCFF;
            border: thick solid #808080;
            border-radius: 10px;
            min-height: 250px;
            position: relative;
            margin: auto;
            width: 40%;
            padding: 10px;
        }

        .content {
            position: absolute;
            margin: auto;
            width: 90%;
            padding: 10px;
            bottom: 15px;
            left: 30px;
        }

        div {
            overflow: auto;
        }
        
    </style>
</head>
<body>
    <p align="center"><strong>To connect the web client, reload this page after a server is started</strong></p>
    <div class="container">
        <div style="height: 350px">
            <ul id="discussion"></ul>
        </div>        
        <div class="content">
            <input type="text" id="message" />
            <input type="button" id="sendmessage" value="Send" />
            <input type="hidden" id="displayname" />
        </div>
    </div>

    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-1.6.4.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.1.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="http://localhost:8080/signalr/hubs"></script>
    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">
        $(function () {
            //Set the hubs URL for the connection
            $.connection.hub.url = "http://localhost:8080/signalr";

            // Declare a proxy to reference the hub.
            var chat = $.connection.myHub;

            // Create a function that the hub can call to broadcast messages.
            chat.client.addMessage = function (name, Msg) {
                $('#discussion').append('<li>' + name + " " + Msg + '</li>');
            };


            // Get the user name and store it to prepend to messages.
            $('#displayname').val("@Model.Username");
            // Set initial focus to message input box.
            $('#message').focus();

            $.connection.hub.start(function () {
                chat.server.join("@Model.Username");
            });

            // Start the connection.
            $.connection.hub.start().done(function () {

                $('#sendmessage').click(function () {

                    chat.server.send($('#displayname').val(), { Msg: $('#message').val(), Group: "@Model.Username" });

                    // Call the Send method on the hub.
                    //chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment.
                    $('#message').val('').focus();
                });
            });
        });
    </script>
</body>
</html>